---
dist: trusty
language: python
python:
  - "2.7"

# Use the new container infrastructure
sudo: false

env:
  - ANSIBLE_VERSION=2.7.10
  - ANSIBLE_VERSION=2.4.6.0

install:
  # Install ansible
  - pip install ansible==$ANSIBLE_VERSION

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
