---
# tasks file for s3_vars
- block:
  - name: store config file destination path on localhost as variable
    set_fact:
      s3_vars_config_local_file: "{{ s3_vars_config_local_dir + '/' + s3_vars_config_local_file_name }}"

  - name: ensure config file destination directory exists
    file:
        path: "{{ s3_vars_config_local_file | dirname }}"
        state: directory

  - name: download config from s3
    s3:
      aws_access_key: "{{ s3_vars_aws_access_key | d(omit) }}"
      aws_secret_key: "{{ s3_vars_aws_secret_key | d(omit) }}"
      profile: "{{ s3_vars_aws_profile | d(omit) }}"
      bucket: "{{ s3_vars_bucket }}"
      object: "{{ s3_vars_object }}"
      dest: "{{ s3_vars_config_local_file }}"
      overwrite: different
      mode: get

  - name: turn config file into variables
    include_vars:
      file: "{{ s3_vars_config_local_file }}"

  - name: delete config file from localhost
    file:
      path: "{{ s3_vars_config_local_file }}"
      state: absent
    when: s3_vars_config_cleanup|bool

  delegate_to: 127.0.0.1
  run_once: true
  become: false
